=== leryunard/xmlvalido_GRUPO06/Ejercicios/dtd_externa/ejercicio-II-2b-dtd/fichero.dtd
<!-- Hoja.dtd -->
<!ELEMENT fichero (ficha+)>
		<!ELEMENT ficha (nombre, apellido, NIT, carnet, DUI)>
		<!ELEMENT nombre (#PCDATA)>
		<!ATTLIST nombre sexo (masculino|femenino) #REQUIRED>
    <!ATTLIST nombre edad  CDATA  #IMPLIED>
		<!ELEMENT apellido (#PCDATA)>
		<!ELEMENT NIT (#PCDATA)>
		<!ELEMENT carnet (#PCDATA)>
		<!ELEMENT DUI (#PCDATA)>

=== leryunard/xmlvalido_GRUPO06/Ejercicios/dtd_externa/ejercicio-II-2b-dtd/ejercicio-ii-2b-dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="estilo ejercicio-ii-2b-dtd.css" ?>
<!-- Ejercicio II.2b..xml Grupo06 -->

<!DOCTYPE Registro SYSTEM "fichero.dtd">
<fichero>
 <ficha>
  <nombre sexo="masculino" edad="24">Carlos</nombre>
  <apellido>Vasquez</apellido>
  <direccion>c/SS, Boulevard Universitario</direccion>
  <carnet>VR16021</carnet>
 </ficha>
 
 <ficha>
  <nombre sexo="masculino" edad="24">Leonardo</nombre>
  <apellido>Efigenio</apellido>
  <direccion>c/SS, Boulevard Universitario</direccion>
  <carnet>EL19004</carnet>
 </ficha>
 
 <ficha>
  <nombre sexo="masculino" edad="24">Wilfredo</nombre>
  <apellido>Mancia</apellido>
  <direccion>c/SS, Boulevard Universitario</direccion>
  <carnet>MT20015</carnet>
 </ficha>
 
 <ficha>
  <nombre sexo="masculino" edad="24">Julio</nombre>
  <apellido>Mejia</apellido>
  <direccion>c/SS, Boulevard Universitario</direccion>
  <carnet>MR20084</carnet>
 </ficha>
 
  <ficha>
  <nombre sexo="masculino" edad="24">Anderson</nombre>
  <apellido>Nieto</apellido>
  <direccion>c/SS, Boulevard Universitario</direccion>
  <carnet>NM19012</carnet>
 </ficha>
 
 <ficha>
  <nombre sexo="masculino" edad="24">Oswaldo</nombre>
  <apellido>Cardoza</apellido>
  <direccion>c/SS, Boulevard Universitario</direccion>
  <carnet>CD15015</carnet>
 </ficha>
 
 <ficha>
  <nombre sexo="masculino" edad="24">Kevin </nombre>
  <apellido>Grande</apellido>
  <direccion>c/SS, Boulevard Universitario</direccion>
  <carnet>GC20029</carnet>
 </ficha>
 
 <ficha>
  <nombre sexo="masculino" edad="24">Carlos</nombre>
  <apellido>Rafaelano</apellido>
  <direccion>c/SS, Boulevard Universitario</direccion>
  <carnet>RS20002</carnet>
 </ficha>
 
  <ficha>
  <nombre sexo="masculino" edad="24">Miguel</nombre>
  <apellido>Galdamez</apellido>
  <direccion>c/SS, Boulevard Universitario</direccion>
  <carnet>GC18090</carnet>
 </ficha>
</fichero>
