<?xml version="1.0" encoding="UTF-8"?>
<!-- Ejercicio II.1a..xml Grupo06 -->

<!DOCTYPE fichero [
		<!ELEMENT fichero (ficha+)>
		<!ELEMENT ficha (nombre, apellido, direccion*, carnet, DUI?)>
		<!ELEMENT nombre (#PCDATA)>
		<!ATTLIST nombre sexo (masculino|femenino) #REQUIRED>
            	<!ATTLIST nombre edad  CDATA  #IMPLIED>
		<!ELEMENT apellido (#PCDATA)>
		<!ELEMENT direccion (#PCDATA)>
		<!ELEMENT carnet (#PCDATA)>
		<!ELEMENT DUI (#PCDATA)>
		]>
<fichero>
 <ficha>
  <nombre sexo="masculino" edad="24">Carlos</nombre>
  <apellido>Vasquez</apellido>
  <direccion>c/SS, Boulevard Universitario</direccion>
  <carnet>VR16021</carnet>
 </ficha>
 
 <ficha>
  <nombre sexo="masculino" edad="24">Leonardo</nombre>
  <apellido>Efigenio</apellido>
  <direccion>c/SS, Boulevard Universitario</direccion>
  <carnet>EL19004</carnet>
 </ficha>
 
 <ficha>
  <nombre sexo="masculino" edad="24">Wilfredo</nombre>
  <apellido>Mancia</apellido>
  <direccion>c/SS, Boulevard Universitario</direccion>
  <carnet>MT20015</carnet>
 </ficha>
 
 <ficha>
  <nombre sexo="masculino" edad="24">Julio</nombre>
  <apellido>Mejia</apellido>
  <direccion>c/SS, Boulevard Universitario</direccion>
  <carnet>MR20084</carnet>
 </ficha>
 
  <ficha>
  <nombre sexo="masculino" edad="24">Anderson</nombre>
  <apellido>Nieto</apellido>
  <direccion>c/SS, Boulevard Universitario</direccion>
  <carnet>NM19012</carnet>
 </ficha>
 
 <ficha>
  <nombre sexo="masculino" edad="24">Oswaldo</nombre>
  <apellido>Cardoza</apellido>
  <direccion>c/SS, Boulevard Universitario</direccion>
  <carnet>CD15015</carnet>
 </ficha>
 
 <ficha>
  <nombre sexo="masculino" edad="24">Kevin </nombre>
  <apellido>Grande</apellido>
  <direccion>c/SS, Boulevard Universitario</direccion>
  <carnet>GC20029</carnet>
 </ficha>
 
 <ficha>
  <nombre sexo="masculino" edad="24">Carlos</nombre>
  <apellido>Rafaelano</apellido>
  <direccion>c/SS, Boulevard Universitario</direccion>
  <carnet>RS20002</carnet>
 </ficha>
 
  <ficha>
  <nombre sexo="masculino" edad="24">Miguel</nombre>
  <apellido>Galdamez</apellido>
  <direccion>c/SS, Boulevard Universitario</direccion>
  <carnet>GC18090</carnet>
 </ficha>
</fichero>
